
name: CI Black Duck security scan

on:
  push:
    branches: [ "master", "uat", "release" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      pull-requests: write
      security-events: write
      actions: read
      
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Black Duck SCA/SAST Scan
        uses: blackduck-inc/black-duck-security-scan@805cbd09e806b01907bbea0f990723c2bb85abe9
        with:
            ### SCANNING: Required fields
            polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
            polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
            polaris_assessment_types: "SCA,SAST"
            
            ### SCANNING: Optional fields
            polaris_application_name: ${{ vars.APP_NAME }}
            polaris_project_name: ${{ github.event.repository.name }}
            
            ### PULL REQUEST COMMENTS: Uncomment below to enable
            polaris_prComment_enabled: true 
            github_token: ${{ secrets.GH_TOKEN }} # Required when PR comments is enabled
